<?php

return [
    'algunos_temas' => 'Karma - Réencarnation - L'Eveil -  Les Peurs et les Emotions Négatives - Méditation et Relaxation - Chakras et Mantras - Personnalité, Essence et Ego - Lois Métaphysiques et Biologie Esotérique - Signification des rêves - Voyage Astral - Kabbale - Intelligence Emotionnelle - Relations Humaines - La sage utilisation de notre énergie - Alchimie - Evolution et Involution',
     
    'informacion_del_curso_1' => 'Cette Institution donne de façon libre et gratuite ses Cours sur l'Auto-connaissance profonde et sur le développement du potentiel humain.',
    'informacion_del_curso_2' => 'C'est un cours à la fois théorique et pratique qui comprend 23 leçons où l'on aborde des thèmes d'une grande profondeur sur la psychologie, l'anthropologie, la philosophie et la métaphysique. Ces leçons nous aident à comprendre que la nature de l'être humain a une plus grande profondeur que celle qu'on lui connaît normalement.',
    'informacion_del_curso_3' => 'Grâce à ce cours, nous pouvons comprendre la structure physique, animique et psychique de l'être humain et entrer dans la connaissance profonde de nos capacités intérieures pour nous développer pleinement mais aussi de la nature intime qui nous limite et conditionne.',
    'algunas_tematicas_1' => 'Dans ce cours, dont est chargé un instructeur certifié par l'Institution, nous commençons un parcours à travers le large éventail de sujets abordés par la connaissance gnostique, où nous trouverons des thèmes tels que :',
    'algunas_tematicas_2' => '- La connaissance intérieure, la sagesse millénaire.',
    'algunas_tematicas_3' => '- Les aspects qui se manifestent dans notre monde intérieur et extérieur : la personnalité, l'Essence et l'ego - L'éveil de la conscience, ses possibilités et la libération psychologique.',
    'algunas_tematicas_4' => '- Les lois les lois métaphysiques qui nous gouvernent et déterminent notre destinée, le Karma et le Dharma, le retour, la récurrence, la réincarnation, l'évolution et l'involution, etc.',
    'algunas_tematicas_5' => '- Nos défauts psychologiques qui nous conditionnent le plus : nos peurs, nos complexes et nos insécurités, nos émotions négatives de haine, de ressentiment, d'envie, de convoitise, nos mauvaises habitudes, nos vices et comportements négatifs. Nous connaîtrons les techniques de connaissance de soi et de découverte de soi pour comprendre ces éléments et les éliminer définitivement de notre vie.',
    'algunas_tematicas_6' => '- Nous connaîtrons aussi notre biologie ésotérique ou interne et parlerons de nos centres psycho-physiologiques, de nos chakras, de notre constitution interne avec ses différents corps et dimensions.',
    'algunas_tematicas_7' => '- Nous développerons des techniques de connaissance de soi pour entrer dans notre monde intérieur et connaître ses merveilles et ses possibilités infinies, nous apprendrons des techniques de relaxation, de concentration, des mantras, des runes, la science pranique, des techniques pour réduire le stress, des techniques de dédoublement astral.',
    'algunas_tematicas_8' => '- Nous parlerons des Relations Humaines, de la façon de nous nourrir correctement, de la façon d'avoir et de produire une énergie adaptée à notre vie, à notre transformation et régénération physique, psychologique et spirituelle. Nous connaîtrons l'alchimie des sages anciens et son sens profond quant à la transformation et le dépassement intérieur.',
    'algunas_tematicas_9' => '',
    'proposito_de_curso_1' => 'Créé dans le but de transmettre un message de vie transformateur et pratique adressé à chaque individu, ce cours de première chambre est un véritable appel à la conscience de l'être humain, pour en promouvoir l'influence sur nos actions et décisions.',
    'proposito_de_curso_2' => 'A travers les différentes rencontres et une didactique centrée sur l'expérience, ce cours souligne l'importance de la découverte de soi que l'homme doit faire par rapport à sa véritable essence, pour réussir ainsi à donner un sens conscient et transcendantal à ses pas dans la vie..',
    'proposito_de_curso_3' => 'Il nous enseigne à entreprendre un travail intérieur qui nous conduit à élargir la notion de qui nous sommes, de notre merveilleuse composition matérielle et spirituelle, de la relation que nous avons avec chaque être vivant, avec la planète et l'univers lui-même..',
    'proposito_de_curso_4' => 'Il nous fournit également des connaissances fondamentales lorsque nous nous proposons de surmonter les obstacles qui entravent actuellement notre harmonie psycho-physique et la libre circulation des capacités que nous portons en nous.',
    'proposito_de_curso_5' => 'Répondre à des questions telles que : qui suis-je ? Où étais-je avant ma naissance ? Qu'y a-t-il au-delà de la mort ? Ce sont des préoccupations naturelles chez toute personne qui a atteint un certain degré de "maturité" intérieure..',
    'proposito_de_curso_6' => 'Les réponses à de telles préoccupations, nous les trouvons autour de l'axe philosophique sur lequel gravite la Gnosis, "Homme connais-toi toi-même',
    'proposito_de_curso_7' => 'C'est par le chemin de la connaissance de soi que nous pouvons avoir une vie plus profonde et plus riche à partir de l'expérience directe et grâce à ce Cours, nous obtiendrons les outils pour parcourir notre propre Chemin.',
    'proposito_de_curso_8' => 'Nous vous attendons.'
];