<?php

return [
    'algunos_temas' => 'Karma - Reencarnación - El Despertar -  Los Miedos y las Emociones Negativas - Meditación y Relajación - Chakras y Mantrams - Personalidad, Esencia y Ego  - Leyes Meta-físicas y Biología Esotérica - Significado de los sueños - Viajes Astrales - Kabala - Inteligencia Emocional - Relaciones Humanas - El sabio uso de nuestra energía - Alquimia  - Evolución e Involución',
    'informacion_del_curso_1' => 'Esta Institución entrega de manera libre y gratuita sus Cursos para el auto-conocimiento profundo y el desarrollo del potencial humano.',
    'informacion_del_curso_2' => 'Es un Curso teórico-práctico de 23 clases, donde se abordan temas de gran profundidad psicológica, antropológica, filosófica y metafísica, ayudándonos a comprender que la naturaleza del ser humano tiene una profundidad mayor a la que conocemos normalmente.',
    'informacion_del_curso_3' => 'Mediante este curso podremos comprender la estructura física, anímica y psíquica del ser humano, y adentrarnos en el conocimiento profundo de nuestras capacidades internas. Pero también de los aspectos psicológicos que nos limitan y condicionan para desarrollarnos plenamente.',
    'algunas_tematicas_1' => 'En este curso, a cargo de instructores avalados por la Institución, iniciamos un recorrido a través de la amplia temática abordada por el conocimiento gnóstico, donde encontraremos temas como:',
    'algunas_tematicas_2' => '- El Conocimiento Interior, la sabiduría milenaria.',
    'algunas_tematicas_3' => '- Los aspectos que se manifiestan en nuestro mundo interior y exterior: la personalidad, la esencia y el ego - El despertar de la conciencia, sus capacidades y la liberación psicológica.',
    'algunas_tematicas_4' => '- Las leyes metafísicas que nos rigen y que determinan nuestro destino, el Karma y Dharma, el retorno, la recurrencia, la reencarnación, la evolución e involución, etc.',
    'algunas_tematicas_5' => '- Nuestros defectos psicológicos más condicionantes: nuestros miedos, complejos e inseguridades, nuestras emociones negativas de odio, rencor, envidia, codicia, nuestros malos hábitos, vicios y conductas negativas. Conoceremos las técnicas de auto-conocimiento y auto-descubrimiento para comprender estos elementos y erradicarlos definitivamente de nuestras vida.',
    'algunas_tematicas_6' => '- Conoceremos también nuestra biología esotérica o interna donde hablaremos de nuestros centros psico-fisiológicos, nuestros Chakras, nuestra constitución interna con sus distintos cuerpos y dimensiones.',
    'algunas_tematicas_7' => '- Desarrollaremos técnicas de autoconocimiento para adentrarnos en nuestro mundo interior y conocer sus maravillas y sus infinitas posibilidades, aprenderemos técnicas de relajación, concentración, mantrams, runas, la ciencia pránica, técnicas para reducir el estres, técnicas de desdoblamiento astral.',
    'algunas_tematicas_8' => '- Hablaremos sobre las Relaciones Humanas, sobre como alimentarnos correctamente, sobre como tener y producir una energía apta para nuestra vida y nuestra transformación y regeneración física, psicológica y espiritual, conociendo la alquimia de los antiguos sabios y su sentido profundo de transformación y superación interior.',
    'algunas_tematicas_9' => '',
    'proposito_de_curso_1' => 'Creado con el fin de transmitir un mensaje de vida transformador y práctico, dirigido a todo individuo, este curso de primera cámara es un verdadero llamado a la conciencia del ser humano, que promueve su influencia sobre nuestros actos y decisiones.',
    'proposito_de_curso_2' => 'A través de los distintos encuentros y de una didáctica enfocada en la experiencia, este curso destaca la importancia del auto-descubrimiento que el hombre necesita realizar respecto de su verdadera esencia, para lograr de esta manera dar un rumbo consciente y trascendental a sus pasos en la vida.',
    'proposito_de_curso_3' => 'Nos enseña a emprender un trabajo interno que conduce a expandir nuestra noción respecto de quiénes somos, de nuestra maravillosa composición tanto material como espiritual, de la relación que guardamos con cada ser vivo, con el planeta y el universo en sí.',
    'proposito_de_curso_4' => 'Así también, nos proporciona un conocimiento fundamental al momento de proponernos superar los obstáculos que actualmente impidan nuestra armonía psico-física y el libre fluir de las capacidades que llevamos guardadas dentro de nosotros mismos.',
    'proposito_de_curso_5' => 'Responder a cuestionamientos como ¿Quién soy? ¿dónde estaba antes de nacer? ¿qué hay más allá de la muerte?, son inquietudes naturales en cualquier persona que ha alcanzado un cierto grado de "madurez" interior.',
    'proposito_de_curso_6' => 'Las respuestas a dichas inquietudes las encontramos alrededor del eje filosófico sobre el que gira la Gnosis, "Hombre conócete a tí mismo".',
    'proposito_de_curso_7' => 'Es a través del camino del auto-conocimiento, que podemos tener una vida más profunda y rica desde una vivencia directa; y es por medio de este Curso que obtendremos las herramientas para recorrer nuestro propio Camino.',
    'proposito_de_curso_8' => 'Los esperamos.'
];