<?php

return [
    'algunos_temas' => "Karma - Réincarnation - Eveil de la Conscience - Méditation et relaxation - Chakras et Mantras - Personnalité, Essence et Ego - Lois métaphysiques et biologie ésotérique - Signification des rêves - Voyage astral - Kabbale - Relations humaines - La sage utilisation de notre énergie - Alchimie - Evolution et Involution",     
    'informacion_del_curso_1' => "Cette Institution donne de façon libre et gratuite ses Cours sur l'Auto-connaissance profonde et sur le développement du potentiel humain.",
    'informacion_del_curso_2' => "C'est un cours à la fois théorique et pratique qui comprend 23 leçons où l'on aborde des thèmes d'une grande profondeur sur la psychologie, l'anthropologie, la philosophie et la métaphysique. Ces leçons nous aident à comprendre que la nature de l'être humain a une plus grande profondeur que celle qu'on lui connaît normalement.",
    'informacion_del_curso_3' => "Grâce à ce cours, nous pouvons comprendre la structure physique, animique et psychique de l'être humain et entrer dans la connaissance profonde de nos capacités intérieures pour nous développer pleinement mais aussi de la nature intime qui nous limite et conditionne.",
    'algunas_tematicas_1' => "Dans ce cours, dont est chargé un instructeur certifié par l'Institution, nous commençons un parcours à travers le large éventail de sujets abordés par la connaissance gnostique, où nous trouverons des thèmes tels que :",
    'algunas_tematicas_2' => "- La connaissance intérieure, la sagesse millénaire.",
    'algunas_tematicas_3' => "- Les aspects qui se manifestent dans notre monde intérieur et extérieur : la personnalité, l'Essence et l'ego - L'éveil de la conscience, ses possibilités et la libération psychologique.",
    'algunas_tematicas_4' => "- Les lois métaphysiques qui nous gouvernent et déterminent notre destinée, le Karma et le Dharma, le retour, la récurrence, la réincarnation, l'évolution et l'involution, etc.",
    'algunas_tematicas_5' => "- Nos défauts psychologiques qui nous conditionnent le plus : nos peurs, nos complexes et nos insécurités, nos émotions négatives de haine, de ressentiment, d'envie, de convoitise, nos mauvaises habitudes, nos vices et comportements négatifs. Nous connaîtrons les techniques de connaissance de soi et de découverte de soi pour comprendre ces éléments et les éliminer définitivement de notre vie.",
    'algunas_tematicas_6' => "- Nous connaîtrons aussi notre biologie ésotérique ou interne et parlerons de nos centres psycho-physiologiques, de nos chakras, de notre constitution interne avec ses différents corps et dimensions.",
    'algunas_tematicas_7' => "- Nous développerons des techniques de connaissance de soi pour entrer dans notre monde intérieur et connaître ses merveilles et ses possibilités infinies, nous apprendrons des techniques de relaxation, de concentration, des mantras, des runes, la science pranique, des techniques pour réduire le stress, des techniques de dédoublement astral.",
    'algunas_tematicas_8' => "- Nous parlerons des Relations Humaines, de la façon de nous nourrir correctement, de la façon d'avoir et de produire une énergie adaptée à notre vie, à notre transformation et régénération physique, psychologique et spirituelle. Nous connaîtrons l'alchimie des sages anciens et son sens profond quant à la transformation et le dépassement intérieur.",
    'algunas_tematicas_9' => "",
    'proposito_de_curso_1' => "Créé dans le but de transmettre un message de vie transformateur et pratique adressé à chaque individu, ce cours de première chambre est un véritable appel à la conscience de l'être humain, pour en promouvoir l'influence sur nos actions et décisions.",
    'proposito_de_curso_2' => "A travers les différentes rencontres et une didactique centrée sur l'expérience, ce cours souligne l'importance de la découverte de soi que l'homme doit faire par rapport à sa véritable essence, pour réussir ainsi à donner un sens conscient et transcendantal à ses pas dans la vie..",
    'proposito_de_curso_3' => "Il nous enseigne à entreprendre un travail intérieur qui nous conduit à élargir la notion de qui nous sommes, de notre merveilleuse composition matérielle et spirituelle, de la relation que nous avons avec chaque être vivant, avec la planète et l'univers lui-même..",
    'proposito_de_curso_4' => "Il nous fournit également des connaissances fondamentales lorsque nous nous proposons de surmonter les obstacles qui entravent actuellement notre harmonie psycho-physique et la libre circulation des capacités que nous portons en nous.",
    'proposito_de_curso_5' => "Répondre à des questions telles que : qui suis-je ? Où étais-je avant ma naissance ? Qu'y a-t-il au-delà de la mort ? Ce sont des préoccupations naturelles chez toute personne qui a atteint un certain degré de 'maturité' intérieure..",
    'proposito_de_curso_6' => "Les réponses à de telles préoccupations, nous les trouvons autour de l'axe philosophique sur lequel gravite la Gnosis, Homme connais-toi toi-même",
    'proposito_de_curso_7' => "C'est par le chemin de la connaissance de soi que nous pouvons avoir une vie plus profonde et plus riche à partir de l'expérience directe et grâce à ce Cours, nous obtiendrons les outils pour parcourir notre propre Chemin.",
    'proposito_de_curso_8' => "Nous vous attendons.",
    'tit_requisito_cursos_whatsapp' => 'Prérequis pour ce cours:',
    'tit_info_requisito_cursos_whatsapp' => "Le seul prérequis est <strong>l'installation de l'application WhatsApp</strong>. Si vous ne l'avez pas sur votre mobile, vous devez la télécharger.  <br><p><strong>Android</strong> Play Store: <a href='https://play.google.com/store/apps/details?id=com.whatsapp' target='_blank'>https://play.google.com/store/apps/details?id=com.whatsapp</a></p> <p><strong>Iphone</strong> App Store: <a href='https://apps.apple.com/app/whatsapp-messenger/id310633997' target='_blank'>https://apps.apple.com/app/whatsapp-messenger/id310633997</a></p> <p>WhatsApp est une application de messagerie gratuite que nous utiliserons comme plateforme pour vous envoyer toutes les leçons du cours.</p>",
    'tit_info_cursos_whatsapp' => 'Méthodologie du cours par WhatsApp',
    'info_cursos_whatsapp' => "Nous allons créer un groupe WhatsApp qui fonctionnera comme notre <strong> salle de classe virtuelle </strong>. Les cours et toutes les informations liées au cours y seront partagés. <br> Seuls les administrateurs pourront partager du matériel. <br> <br> Certains jours, nous ouvrirons la salle de classe virtuelle, pour pouvoir interagir via le chat du groupe, où Nous répondrons à vos questions et préoccupations concernant la dernière leçon publiée. Ce sera l'occasion d'interagir et de revoir notre compréhension du cours. La salle de classe restera ouverte pendant une durée approximative de 3 heures, en fonction de la dynamique du moment. <br> Au fur et à mesure que le cours progresse, nous vous invitons à participer à des pratiques de groupe de relaxation, méditation, rétrospection, entre autres. Nous le ferons grâce à un outil de vidéoconférence ou à des pratiques précédemment enregistrées. <br> <br> Tous les étudiants peuvent interagir à tout moment avec le tuteur désigné <br>",
    'tit_requisito_cursos_instagram' => 'Requisitos para el curso:',
    'tit_info_requisito_cursos_instagram' => 'Para realizar este curso debes <strong>descargarte la app de instagram</strong> si no la tienes instalada en tu teléfono móvil. <br><p><strong>Android</strong> Play Store: <a href="https://play.google.com/store/apps/details?id=com.instagram.android" target="_blank">https://play.google.com/store/apps/details?id=com.instagram.android</a></p> <p><strong>Iphone</strong> App Store: <a href="https://apps.apple.com/us/app/instagram/id389801252" target="_blank">https://apps.apple.com/us/app/instagram/id389801252</a></p> <p>Instagram es un app gratuita que utilizaremos como plataforma para entregarte las lecciones de este curso.</p>',
    'tit_info_cursos_instagram' => 'Metodología del curso por Instagram',
    'info_cursos_instagram' => '<strong>Registrate en este formulario y luego seguí nuestra cuenta de Instagram <a href="https://www.instagram.com/gnosisenvivo/" target="_blank">@gnosisenvivo</a></strong> donde reicibirás las lecciones semanalmente en sesiones en vivo, podrás hacer tus preguntas, entregaremos dinámicas, videos y material complementario. Todo desde la misma cuenta.<br>',
    'info_mail_invitacion_curso_online' => "L'Institut Gnostique vous propose son cours de connaissance de soi en ligne. Ce cours est offert en personne dans nos institutions à travers le monde depuis plus de 50 ans, et maintenant nous vous le proposons à 100% à distance. L'objectif est que vous connaissiez et étudiez de manière ordonnée les fondements de l'enseignement gnostique et provoquiez ainsi dans votre vie une transformation réelle et profonde dans la manière de penser, de ressentir et d'agir, afin de prendre des mesures conscientes et transcendantales dans votre vie . Ce cours est une introduction et comprend 17 classes initiales, qui seront enseignées via des liens YouTube privés que nous vous enverrons via l'un de nos canaux disponibles: Google Classroom, Facebook Groups ou WhatsApp Groups qui seront en charge de nos tuteurs. S'inscrire! Les quotas sont limités (en raison du nombre limité de tuteurs).",
    'explicacion_modalidad_notificacion_de_asistencia_1' => "IMPORTANT : après avoir terminé de regarder toutes les vidéos de la leçon, vous devez nous en informer en saisissant le lien de notification que nous vous enverrons avec chaque leçon, (vous aurez besoin du code étudiant  envoyé à chacun d'entre vous dans le message personnel de bienvenue ).",
    'explicacion_modalidad_notificacion_de_asistencia_2' => "IMPORTANT : après avoir regardé toutes les vidéos de la leçon, vous devrez nous en informer en utilisant un lien que nous vous aurons envoyé avec la leçon correspondante. Il s'agit d'un lien qui vous mènera à WhatsApp, il est donc important que vous fassiez cela depuis votre téléphone portable.",
];





