<?php

return [
    'algunos_temas' => 'Karma - Reencarnação - O Despertar -  Os Medos e as Emoções Negativas - Meditação e Relaxamento - Chakras e Mantrans - Personalidade, Essência e Ego  - Leis Metafísicas e Biologia Esotérica - Significado dos sonhos - Viagens Astrais - Kabala - Inteligência Emocional - Relações Humanas - O sábio uso de nossas energias - Alquimia  - Evolução e Involução',
    'informacion_del_curso_1' => 'Esta Instituição oferece  de maneira gratuita seus cursos para o autoconhecimento e para o desenvolvimento profundo do  potencial humano.',
    'informacion_del_curso_2' => 'É um curso teórico-prático de 23 aulas, que aborda temas de grande profundidade psicológica, antropológica, filosófica e metafísica, ajudando-nos a compreender que a natureza do ser humano tem uma profundidade maior do que normalmente conhecemos.',
    'informacion_del_curso_3' => 'Através deste curso, podemos compreender a estrutura física, anímica e psíquica do ser humano, e adentrar no conhecimento profundo de nossas capacidades internas, etambém sobre como dominar nossa natureza interior que muitas vezes nos limita e nos condiciona impedindo nosso desenvolvimento completo.',
    'algunas_tematicas_1' => 'Neste curso, ditado por instrutores certificados pela instituição, iniciaremos uma viagem através da ampla temática abordada pelo conhecimento gnóstico, onde encontramos temas como:',
    'algunas_tematicas_2' => '- O Conhecimento Interior,  e a Sabedoria Milenar;',
    'algunas_tematicas_3' => '- Os aspectos psicológicos de nosso mundo interiorr: personalidade, essência e ego;',
    'algunas_tematicas_4' => '- O despertar da consciência, suas capacidades e liberdade psicológica;',
    'algunas_tematicas_5' => '- As leis metafísicas que nos regem e que determinam nosso destino, Karma e Dharma, Retorno, Recorrência, Reencarnação, Evolução e Involução, etc... E como manejá-las conscientemente à nosso favor;',
    'algunas_tematicas_6' => '- Os defeitos psicológicos que mais condicionam nossa vida: nossos medos, complexos e inseguranças, nossas emoções negativas de ódio, rancor, ressentimento, a inveja, a cobiça, nossos maus hábitos, vícios e comportamentos negativos. Conheceremos as técnicas de autoconhecimento e auto-descobrimento para compreender esses elementos e erradicá-los definitivamente de nossas vidas.',
    'algunas_tematicas_7' => '- Conheceremos também nossa biologia esotérica ou interna onde falaremos de nossos centros psicofisiológicos, nossos Chakras, nossa constituição interna com seus diferentes corpos e dimensões.',
    'algunas_tematicas_8' => '- Vamos desenvolver técnicas de auto-conhecimento para adentrar em nosso mundo interior e conhecer suas maravilhas e suas infinitas possibilidades, aprenderemos técnicas de relaxamento, concentração, mantrans, runas, ciência Prânica, técnicas para reduzir o stress, técnicas de projeção astral.',
    'algunas_tematicas_9' => '- Vamos falar sobre relações humanas, sobre como nos alimentar corretamente, sobre como obter e produzir uma energia apta para nossas vidas, nossa transformação e regeneração de física, psicológica e espiritual, conhecendo a alquimia dos  antigos sábios e seu sentido profundo de transformação e superação interior.',
    'proposito_de_curso_1' => 'Criado com a finalidade de transmitir uma mensagem de vida transformadora e prática, dirigida a todos os indivíduos, este curso de Autoconhecimento (Primeira Câmara) é um verdadeiro chamado à consciência do ser humano, que promove sua influência em nossos atos e decisões.',
    'proposito_de_curso_2' => 'Através de  distintos encontros e de uma  didática enfocada na experimentação, este curso destaca a importância do auto-descobrimento, o qual o homem necessita para realizar sua verdadeira essência, para conseguir, assim, dar um rumo consciente e transcendental para os seus passos na vida.',
    'proposito_de_curso_3' => 'Ensina-nos a empreender um trabalho interior que nos leva à expandir a nossa noção sobre quem somos, sobre nossa maravilhosa composição tanto material como espiritual, sobre a relação que temos com cada ser vivo, com o planeta e com o próprio universo.',
    'proposito_de_curso_4' => 'Também nos proporciona um conhecimento fundamental que nos propõe superar os obstáculos que atualmente impedem nossa harmonia psicofísica e o livre fluir das capacidades que levamos guardades em nós mesmos.',
    'proposito_de_curso_5' => 'Responder à questões como: "Quem sou? Onde estava antes de nascer? O que há além da morte?"; São preocupações naturais de qualquer pessoa que tenha alcançado um certo grau de "maturidade" interior.',
    'proposito_de_curso_6' => 'As respostas para ditas inquietudes são encontradas em torno do eixo filosófico sobre o qual gira a Gnosis: "O homem conhece a ti mesmo".',
    'proposito_de_curso_7' => 'É através do caminho do autoconhecimento que podemos ter uma vida mais profunda e rica a partir de uma experiência direta; e é através deste Curso que obteremos as ferramentas para percorrer o nosso próprio Caminho.',
    'proposito_de_curso_8' => 'Os Esperamos.',
    'tit_requisito_cursos_whatsapp' => 'Requisito para o curso:',
    'tit_info_requisito_cursos_whatsapp' => 'Para fazer este curso, você deve <strong> baixar o aplicativo WhatsApp</strong> , caso não o tenha instalado no seu celular. <br><p><strong>Android</strong> Play Store: <a href="https://play.google.com/store/apps/details?id=com.whatsapp" target="_blank">https://play.google.com/store/apps/details?id=com.whatsapp</a></p> <p><strong>Iphone</strong> App Store: <a href="https://apps.apple.com/app/whatsapp-messenger/id310633997" target="_blank">https://apps.apple.com/app/whatsapp-messenger/id310633997</a></p> <p>O WhatsApp é um aplicativo de mensagens gratuito que usaremos como plataforma para fornecer as lições deste curso.</p>',
    'tit_info_cursos_whatsapp' => 'Metodologia do curso pelo WhatsApp',
    'info_cursos_whatsapp' => 'Crie um grupo de WhatsApp que funcione como nova <strong> Aula Virtual </strong>. Na parte que separa as Clases e todas as informações úteis sobre o curso. <br> Sólo os requisitos do material do compartimento. <br> <br> Cálculos, medidas da cobertura do Aula Virtual, para poder interagir pelo bate-papo do grupo, grupo contestar suas orações e consultas com relação à última publicação publicada. Esta será a oportunidade para interagir e revisar como está a nova compressão do curso. A Aula permanece aberta por um tempo aproximado de 3 horas, dependendo da dinâmica do momento <br> <br> Na medida em que avança o curso, vamos convidar para participar de práticas grupais de relacionamento, meditação, retrospectiva, entre outras. Você está lendo usando a videoconferência ou práticas práticas da alguna. <br> <br> Todo o conteúdo pode ser interativo no momento oportuno com o tutor designado.<br>',
    'tit_requisito_cursos_instagram' => 'Requisitos para el curso:',
    'tit_info_requisito_cursos_instagram' => 'Para realizar este curso debes <strong>descargarte la app de instagram</strong> si no la tienes instalada en tu teléfono móvil. <br><p><strong>Android</strong> Play Store: <a href="https://play.google.com/store/apps/details?id=com.instagram.android" target="_blank">https://play.google.com/store/apps/details?id=com.instagram.android</a></p> <p><strong>Iphone</strong> App Store: <a href="https://apps.apple.com/us/app/instagram/id389801252" target="_blank">https://apps.apple.com/us/app/instagram/id389801252</a></p> <p>Instagram es un app gratuita que utilizaremos como plataforma para entregarte las lecciones de este curso.</p>',
    'tit_info_cursos_instagram' => 'Metodología del curso por Instagram',
    'info_cursos_instagram' => '<strong>Registrate en este formulario y luego seguí nuestra cuenta de Instagram <a href="https://www.instagram.com/gnosisenvivo/" target="_blank">@gnosisenvivo</a></strong> donde reicibirás las lecciones semanalmente en sesiones en vivo, podrás hacer tus preguntas, entregaremos dinámicas, videos y material complementario. Todo desde la misma cuenta.<br>',
    'info_mail_invitacion_curso_online' => 'O Instituto Gnosis Brasil oferece seu Curso de Autoconhecimento na modalidade Online. Esse curso já é oferecido presencialmente em todas as nossas 110 sedes por todo Brasil há mais de 30 anos, e agora é oferecido de forma 100% remota. O objetivo é que você conheça e estude, de forma ordenada, os fundamentos do ensinamento gnóstico desta Escola de Mistérios; e assim provocar em sua vida uma transformação real e profunda nas formas de pensar, sentir e agir; buscando dar passos conscientes e transcendentais em sua vida e possui aproximadamente 30 aulas, que serão dadas por links privados no Youtube e WhatsaApp. Inscreva-se! Vagas limitadas (devido ao número limitado de tutores).',
    'explicacion_modalidad_notificacion_de_asistencia_1' => '',
    'explicacion_modalidad_notificacion_de_asistencia_2' => '',

];





