<?php

return [
    'algunos_temas' => 'Karma - Reinkarnation - Das Erwachen - Die Ängste und die Negativen Emotionen - Meditation und Entspannung - Chakren und Mantren - Persönlichkeit, Essenz und Ego - Meta-physikalische Gesetze und Esoterische Biologie - Bedeutung der Träume - Astralreisen - Kabala- Emotionale Intelligenz - Menschliche Beziehungen - Die sinnvolle Nutzung unserer Energie - Alchemie - Evolution und Involution',
    'informacion_del_curso_1' => 'Diese Institution bietet frei und kostenlos ihre Kurse für tiefgehende Selbsterkenntnis und die Entwicklung des menschlichen Potentials an.',
    'informacion_del_curso_2' => 'Es ist ein theoretisch-praktischer Kurs mit 23 Unterrichtseinheiten, in dem Themen von großer psychologischer, anthropologischer, philosophischer und metaphysischer Tiefe behandelt werden, die uns helfen zu verstehen, dass die Natur des Menschen weitaus tiefgehender ist, als uns normalerweise bekannt ist.',
    'informacion_del_curso_3' => 'Durch diesen Kurs werden wir in der Lage sein, die physische, animische und psychische Struktur des Menschen zu verstehen und einzutreten in die tiefgründige Kenntnis unserer inneren Fähigkeiten - aber auch der psychologischen Aspekte, die uns in unserer vollständigen Entwicklung einschränken und konditionieren.',
    'algunas_tematicas_1' => 'In diesem Präsenzkurs, der von der Institution geprüften Lehrern geleitet wird, beginnen wir eine Reise durch das breite Themenfeld, das vom gnostischem Wissen angesprochen wird, in dem wir Themen finden werden wie:',
    'algunas_tematicas_2' => '- Inneres Wissen, tausendjährige Weisheit.',
    'algunas_tematicas_3' => '- Die Aspekte, die sich in unserer inneren und äußeren Welt manifestieren: Persönlichkeit, Essenz und Ego - Das Erwachen des Bewusstseins, seine Fähigkeiten und die psychologische Befreiung.',
    'algunas_tematicas_4' => '- Die metaphysischen Gesetze, die uns regieren und die unser Schicksal bestimmen, Karma und Dharma, die Rückkehr, die Wiederholung, die Reinkarnation, die Evolution und die Involution, usw.',
    'algunas_tematicas_5' => '- Unsere uns am stärksten konditionierenden psychologischen Defekte: unsere Ängste, Komplexe und Unsicherheiten, unsere negativen Gefühle von Hass, Groll, Neid, Gier, unsere schlechten Angewohnheiten, Laster und unser negatives Verhalten. Wir werden die Techniken der Selbsterkenntnis und der Selbstfindung kennenlernen, um diese Elemente zu begreifen und sie schließlich endgültig aus unserem Leben auszumerzen.',
    'algunas_tematicas_6' => '- Wir werden ebenso unsere esoterische oder interne Biologie kennen lernen, wobei wir über unsere psycho-physiologischen Zentren, unsere Chakren, unsere innere Konstitution mit ihren verschiedenen Körpern und Dimensionen sprechen werden.',
    'algunas_tematicas_7' => '- Wir werden Techniken der Selbsterkenntnis entwickeln, um in unsere innere Welt einzutreten und ihre Wunder und unendlichen Möglichkeiten kennenzulernen. Wir lernen Entspannungstechniken, Konzentration, Mantren, Runen, Pranische Wissenschaft, Techniken zur Stressreduzierung und Techniken der Beherrschung des Astralkörpers.',
    'algunas_tematicas_8' => '- Es wird über die menschlichen Beziehungen gesprochen, wie wir uns richtig ernähren, wie wir eine Energie haben und produzieren können, die für unser Leben und unsere Transformation und körperliche, psychische und spirituelle Regeneration geeignet ist, und wir lernen die Alchemie der alten Weisen und ihren tiefen Sinn der inneren Transformation und Überwindung kennen.',  
    'algunas_tematicas_9' => '',
    'proposito_de_curso_1' => 'Geschaffen, um eine praktische, lebensverändernde Botschaft zu vermitteln, gerichtet an alle Personen, ist dieser Kurs der ersten Kammer ein wahrer Aufruf an das Bewusstsein bzw. Gewissen des Menschen, das seinen Einfluss auf unsere Handlungen und Entscheidungen ausübt.',
    'proposito_de_curso_2' => 'Innerhalb der verschiedenen Begegnungen und durch eine auf Erfahrungen ausgerichtete Didaktik wird in diesem Kurs die Bedeutung der Selbstfindung hervorgehoben, die der Mensch in Bezug auf sein wahres Wesen ausführen muss, um so einen bewussten und transzendentalen Schritt auf seinem Lebensweg zu tun.',
    'proposito_de_curso_3' => 'Er lehrt uns, eine innere Arbeit zu beginnen, die dazu führt, unsere Vorstellung davon zu erweitern, wer wir sind, von unserer wunderbaren Zusammensetzung, sowohl materiellen als auch geistigen, über die Beziehung, die wir zu jedem Lebewesen haben, zum Planeten und zum Universum an sich.', 
    'proposito_de_curso_4' => 'So vermittelt er uns auch ein grundlegendes Wissen für den Moment, ab dem wir uns vornehmen, die Hindernisse zu überwinden, die derzeit unsere psycho-physische Harmonie und das freie Fließen der Fähigkeiten, die wir in uns aufbewahrt tragen, verhindern.',
    'proposito_de_curso_5' => 'Fragen zu beantworten wie: Wer bin ich? Wo war ich, bevor ich geboren wurde? Was ist jenseits des Todes?, diese sind natürliche innere Unruhen einer jeden Person, die einen gewissen Grad an innerer "Reife" erreicht hat.',
    'proposito_de_curso_6' => 'Die Antworten auf diese Fragestellungen befinden sich im Umfeld der philosophischen Achse, um die sich die Gnosis dreht: "Mensch lerne dich selbst kennen.',
    'proposito_de_curso_7' => 'Über den Weg der Selbsterkenntnis können wir durch eine direkte Erfahrung ein tieferes und reicheres Leben führen; und mittels dieses Kurses erhalten wir die Werkzeuge, um unseren eigenen Weg zu gehen.',
    'proposito_de_curso_8' => 'Wir erwarten Sie.'
];
